// books.js
const books = [
  {
    id: 1,
    title: "Belajar JavaScript Dasar",
    author: "Sabian Vasyelino",
    year: 2021,
    description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 2,
    title: "React untuk Pemula",
    author: "Faisa Al Farrel",
    year: 2022,
    description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 3,
    title: "HTML dan CSS untuk Pemula",
    author: "Zaidaan Salman Saafiq",
    year: 2020,
    description: "Belajar membangun tampilan website dari struktur HTML hingga styling CSS.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 4,
    title: "Node.js dan Express Praktis",
    author: "Achmad Muflih Alrasyid",
    year: 2022,
    description: "Membuat server dan API sederhana menggunakan Node.js dan Express.",
    image: "https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 5,
    title: "Belajar Git dan GitHub",
    author: "Azzam Firdaus",
    year: 2021,
    description: "Mengelola versi kode dan berkolaborasi dalam tim dengan Git dan GitHub.",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 6,
    title: "Dasar-Dasar Basis Data MySQL",
    author: "M. Ridwan Karim",
    year: 2019,
    description: "Memahami konsep tabel, relasi, dan query SQL untuk pengelolaan data.",
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 7,
    title: "Pemrograman Python untuk Pemula",
    author: "Rohmat Hidayat",
    year: 2023,
    description: "Pengenalan bahasa Python lengkap dengan latihan soal yang mudah diikuti.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 8,
    title: "Desain Antarmuka dengan Bootstrap 5",
    author: "Farid Hidayat",
    year: 2023,
    description: "Membuat tampilan website responsif dengan cepat menggunakan Bootstrap 5.",
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 9,
    title: "Struktur Data dan Algoritma",
    author: "Rakha Hidayatulloh",
    year: 2017,
    description: "Dasar berpikir logis dan efisien dalam memecahkan masalah pemrograman.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 10,
    title: "e-Learning: Struktur Data dan Algoritma",
    author: "Lyno Fadillah",
    year: 2019,
    description: "Dasar berpikir logis dan efisien dalam memecahkan masalah pemrograman.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 11,
    title: "Belajar Struktur Data dan Algoritma",
    author: "Marselino",
    year: 2024,
    description: "Belajar Struktur Data dan Algoritma untuk pemula dengan contoh-contoh yang mudah dipahami.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 12,
    title: "HTML dan CSS untuk Pemula",
    author: "Ali Timothy",
    year: 2016,
    description: "Pengenalan dasar HTML dan CSS untuk pemula.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=400&q=80",
  },
];

export default books;
